# Numpy Tutorial Notebook

## What is Numpy ? 
<br>
Numpy is a python library that is used for computing scientific/mathematical data. It is important to note that Numpy can be easily confused with a module or framework but it's a library. Other uses are in:

- Numerical Analysis
- Linear algebra
- Matrix computations

References: https://docs.scipy.org/doc/numpy/user/quickstart.html https://www.tutorialspoint.com/numpy/index.htm

## Imports 

In [1]:
import numpy as np

## Arrays

In [2]:
# Creating an array
a = np.array([1, 2, 3])
# Checking the data type
print(type(a))
# Checking the dimension of the array
print(a.shape)
# Printing individual elements and assigning new values
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
# Creating 2d array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [5]:
# Creating array of zeros
a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
# Creating array of ones
b = np.ones((1, 2))
print(b)

[[1. 1.]]


In [4]:
# Creating array with same values in whole array
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [5]:
# Creating a diagonal matrix
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [6]:
# Creating a random matrix
e = np.random.random((2, 2))
print(e)

[[0.58084583 0.33409276]
 [0.70456968 0.71025724]]


## Array indexing
array_name[from:to]

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [8]:
# Creating a subset of array a
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [9]:
# Reassigning value to the subset changes the value in the original array too
b[0, 0] = 77
print(a[0, 1])
print(b[0,0])

77
77


In [10]:
# Row Indexing
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [11]:
# Column Indexing
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [13]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
b = np.array([0, 2, 0, 1])
print(b)
print(a[np.arange(4), b])


[0 2 0 1]
[ 1  6  7 11]


In [15]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [16]:
a = np.array([[1, 2], [3, 4], [5, 6]])
book_idx = (a > 2)
print(book_idx)
print(a[book_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

In [17]:
x = np.array([1, 2])
print(x.dtype)

int32


In [18]:
x = np.array([1.0, 2.0])
print(x.dtype)

float64


In [19]:
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64


## Linear Algebra

### Matrices Addition

In [20]:
# Matrices Addition
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y) 
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


### Matrices Substraction

In [21]:
# Subtraction of arrays
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


### Matrices Substraction

In [23]:
# Division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Square root

In [24]:
# Square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Dot Product 

In [25]:
# Dot product
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))


219
219


In [26]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [27]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [28]:
# Addition row/column wise
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


### Transpose of a Matrix

In [29]:
# Transposing an array
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [30]:
v = np.array([1, 2, 3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


### Inverse of Matrix 

In [31]:
#Inverse of a matrix
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
print(a) 
ainv = np.linalg.inv(a) 

print('Inverse of a:') 
print(ainv)  

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
Inverse of a:
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]


### Determinant of a Matrix 

In [37]:
# Determinant of a Matrix
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print(b) 
detB = np.linalg.det(b) 
print('Determinant of b:') 
print(detB)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Determinant of b:
-306.0


## External links for deep dive: 
<br> 
http://cs231n.github.io/python-numpy-tutorial/ <br> 
<br> 
https://www.tutorialspoint.com/numpy <br> 
<br> 
https://www.python-course.eu/numpy.php <br> 
<br> 
https://www.youtube.com/watch?v=8Mpc9ukltVA <br> 
<br> 
https://www.youtube.com/watch?v=8JfDAm9y_7s <br> 
